baseURL = 'https://example.org/'
languageCode = 'ar-sa'
title = 'رحيق السنة'

theme ='hugo-book'


[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'dark'
  BookToC = true
  BookSection =  '_'
  BookPortableLinks =true

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1