baseURL = '/'
languageCode = 'ar-sa'
title = 'رحيق السنة'

theme ='hugo-book-o'


[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'
  BookToC = true
  BookSection =  '_'
  BookPortableLinks =true
  BookServiceWorker = true

[markup]

  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe= true